### PR TITLE
Added permalinks to script.js

### PR DESCRIPTION
**Pull request by alinsen**
This is the javascript to create permalinks. The styling (size, hover, color, etc.) will be changed in css later.

### CODE REVIEW

**Comment by apexskier** [comment]
I've got a couple notes, lets talk about them in person.

**Comment by alinsen** [comment]
Changed the javascript based on what we talked about. Looks to be working as desired.

**Comment by apexskier** [comment]
Looks good. I just need to actually test. Then we can add css once the test install's working.

Resolves issue #72

**Comment by apexskier** [comment]
Tested, now to do css.

**Comment by apexskier** [comment]
Replaced by #80. Please close.

**Pull request merged**
