### PR TITLE
fix 2 graphical bug. (TODO minimify the css file)

### PR DESCRIPTION
**Pull request by border0464111**
Line 6880, removing padding fix the way too big buttons here : http://imgur.com/k13zQAV
Line 7159, fix the onl-line text area when editing a page : http://imgur.com/TarwdnQ

TODO: I did not minimify the .min. file. 

Im not shure how I am suppose to do minimify the file in order to be consistant with what's already here . If you wish, explain me how to do it, reject my pull request and I will do it.

### CODE REVIEW

**Comment by apexskier** [comment]
You'll need to make these changes in a fork of the [bootstrap submodule](https://github.com/apexskier/bootstrap/tree/starterbootstrap) and submit a pull request there as well.

Your first change will go here: https://github.com/apexskier/bootstrap/blob/starterbootstrap/less/dokuwiki/buttons.less#L5
Your second here: https://github.com/apexskier/bootstrap/blob/starterbootstrap/less/dokuwiki/editor.less#L14

You'll need to add overriding css after the bootstrap mixins that are being used, or add more specific classes.

If I remember right, you can then run `grunt build` (after `npm install && bower install`) to build and minifiy the css.

**Comment by border0464111** [comment]
Thx. I did edit the .less files and minifiy the css files and test it. It's all good :) 
I will now rdy to push it. but it look nasty in the .less contex. 

https://github.com/border0464111/bootstrap/commit/5e6ff30bd1c9535c7c1f302ab92a555f73b829d9
https://github.com/border0464111/bootstrap/commit/cab8c67f0a13d135f70023dc8100a3d8f834ea4c

im not used to .less but in the second commit, L3,4  this code looks like an infinite loop to me
<code>
.btn {
   .btn; 
</code>

But I not gonna put more time on it. So I might be better to just fill a bug report instead of pushing  ?

**Comment by apexskier** [comment]
That looks fine to me. Go ahead and open a PR on the bootstrap repo to the starterbootstrap branch and I'll take a look and figure out the rest of the merge. If you can, run the grunt command first.

**Comment by apexskier** [comment]
Close when #80 merged.

**Pull request merged**
